# Generated by Django 2.2.2 on 2020-02-28 01:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='title', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='write_up',
            field=models.TextField(default='writeup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='related_titles',
            field=models.ManyToManyField(to='core.Book'),
        ),
        migrations.AddField(
            model_name='author',
            name='works',
            field=models.ManyToManyField(to='core.Book'),
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='core.Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='subjects',
            field=models.ManyToManyField(to='core.Subject'),
        ),
    ]
