# Generated by Django 3.0.3 on 2020-02-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='external_link',
            field=models.URLField(default='link'),
            preserve_default=False,
        ),
    ]
