# Generated by Django 3.0.3 on 2020-03-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200301_0237'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='book',
            name='imagefile',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
