# Generated by Django 3.0.3 on 2020-03-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200301_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='img', upload_to='img'),
        ),
    ]
