# Generated by Django 3.0.3 on 2020-03-02 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
