# Generated by Django 3.0.3 on 2020-03-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200302_1525'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='genre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
